#!/usr/bin/env python3

import sys

ACCEPTABLE_CHARS = ['"┘"', '"┐"', '"└"', '"┌"']

lines = []
for line in sys.stdin:
    lines.append(line)

lines = [s[:-1] for s in lines]

for line in lines:
    if line not in ACCEPTABLE_CHARS:
        print('"unacceptable input"')
        sys.exit(1)

valid_symbols = [s[1] for s in lines]
final_string = '"' + "".join(valid_symbols) + '"'
print(final_string)